version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - hoho4190

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - hoho4190
