name: JaCoCo Badge
description: |
  Generate JaCoCo code coverage badge.
author: hoho4190
inputs:
  token:
    description: github token
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: red
  icon: bold
