name: PR event trigger
on:
  pull_request:
    types:
      - opened

jobs:
  pr_opened:
    name: PR opened
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
  
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Run Issue PR Labeler
        uses: hoho4190/issue-pr-labeler@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file-name: issue-pr-labeler-config.yml
        
      - name: Assign 🙆 assignees to the PR
        uses: toshimaru/auto-author-assign@v1.6.2
